import { DirectionService } from '../../../core/direction.service';
import { OfferingPdfLabels } from './offering-pdf';

/** Shared i18n labels for the school-facing Offering PDF document. */
export function buildOfferingPdfLabels(i18n: DirectionService): OfferingPdfLabels {
  const t = (key: string) => i18n.t(key);
  return {
    brand: t('brand.name'),
    documentTitle: t('partnerships.schoolPartnershipOffering'),
    initiative: t('partnerships.pdfTagline'),
    preparedFor: t('partnerships.pdfPreparedFor'),
    confidential: t('partnerships.pdfConfidential'),
    pageOf: t('partnerships.pdfPageOf'),
    basedOnProgram: t('partnerships.basedOnProgram'),
    overview: t('partnerships.offeringSectionOverview'),
    audience: t('partnerships.offeringSectionAudience'),
    delivery: t('partnerships.offeringSectionDelivery'),
    schedule: t('partnerships.offeringSectionSchedule'),
    curriculum: t('partnerships.offeringSectionCurriculum'),
    learningExperience: t('partnerships.offeringSectionLearning'),
    objectives: t('partnerships.programSectionObjectives'),
    activities: t('partnerships.programSectionActivities'),
    projects: t('partnerships.offeringSectionProjects'),
    sampleProjects: t('partnerships.sampleProjects'),
    finalProject: t('partnerships.finalProject'),
    assessment: t('partnerships.offeringSectionAssessment'),
    requirements: t('partnerships.offeringSectionRequirements'),
    outcomes: t('partnerships.offeringSectionOutcomes'),
    offeringName: t('partnerships.offeringName'),
    programName: t('partnerships.selectProgram'),
    targetAge: t('partnerships.targetAge'),
    targetGrades: t('partnerships.targetGrades'),
    level: t('partnerships.programLevel'),
    profile: t('partnerships.learnerProfile'),
    schoolValue: t('partnerships.schoolValue'),
    studentValue: t('partnerships.studentValue'),
    deliveryFormat: t('partnerships.deliveryFormat'),
    deliveryMode: t('partnerships.deliveryMode'),
    duration: t('partnerships.duration'),
    sessions: t('partnerships.numberOfSessions'),
    sessionLength: t('partnerships.sessionDurationMinutes'),
    sessionFrequency: t('partnerships.sessionFrequency'),
    groupSize: t('partnerships.groupSizeMin'),
    groups: t('partnerships.numberOfGroups'),
    location: t('partnerships.locationNotes'),
    instructor: t('partnerships.instructorRequirement'),
    coordinator: t('partnerships.coordinatorRequirement'),
    assessmentFrequency: t('partnerships.assessmentFrequency'),
    reporting: t('partnerships.reporting'),
    studentProgressReport: t('partnerships.studentProgressReport'),
    schoolSummaryReport: t('partnerships.schoolSummaryReport'),
    expectedOutput: t('partnerships.expectedOutput'),
    evaluation: t('partnerships.evaluationMethod'),
    required: t('partnerships.requirementRequired'),
    recommended: t('partnerships.requirementRecommended'),
    ctaTitle: t('partnerships.pdfCtaTitle'),
    ctaExplore: t('partnerships.pdfCtaExplore'),
    organization: t('partnerships.pdfOrganization'),
    continued: t('partnerships.pdfContinued'),
    minutes: t('partnerships.minutesShort'),
  };
}
