import { DirectionService } from '../../../core/direction.service';
import type { DeliveryPdfLabels } from './delivery-pdf';

/** Shared i18n labels for the Partnership Delivery Report PDF document. */
export function buildDeliveryPdfLabels(i18n: DirectionService): DeliveryPdfLabels {
  const t = (key: string) => i18n.t(key);
  return {
    brand: t('brand.name'),
    documentTitle: t('partnerships.deliveryPdfDocumentTitle'),
    initiative: t('partnerships.pdfTagline'),
    confidential: t('partnerships.pdfConfidential'),
    pageOf: t('partnerships.deliveryPdfPageOf'),
    continued: t('partnerships.pdfContinued'),
    organization: t('partnerships.pdfOrganization'),
    documentControl: t('partnerships.sowPdfDocumentControl'),
    deliveryNo: t('partnerships.deliveryPdfDeliveryNo'),
    sowNo: t('partnerships.sowPdfSowNo'),
    proposalNo: t('partnerships.sowPdfProposalNo'),
    version: t('partnerships.version'),
    status: t('common.status'),
    startDate: t('partnerships.startDate'),
    endDate: t('partnerships.endDate'),
    school: t('partnerships.school'),
    executiveSummary: t('partnerships.deliveryExecutiveSummary'),
    progressOverview: t('partnerships.deliveryProgressOverview'),
    completionChecklist: t('partnerships.deliveryCompletionChecklist'),
    phases: t('partnerships.deliveryPhases'),
    milestones: t('partnerships.deliveryMilestones'),
    sessions: t('partnerships.deliverySessions'),
    groups: t('partnerships.deliveryGroups'),
    team: t('partnerships.deliveryTeam'),
    deliverables: t('partnerships.deliveryDeliverables'),
    issues: t('partnerships.deliveryIssues'),
    raid: t('partnerships.deliveryRaid'),
    communications: t('partnerships.deliveryCommunications'),
    checkpoints: t('partnerships.deliveryCheckpoints'),
    reports: t('partnerships.deliveryReports'),
    overallProgress: t('partnerships.deliveryOverallProgress'),
    sessionsCompleted: t('partnerships.deliveryKpiSessions'),
    studentsEngaged: t('partnerships.deliveryKpiStudents'),
    groupsCount: t('partnerships.deliveryKpiGroups'),
    deliverablesAccepted: t('partnerships.deliveryKpiDeliverables'),
    milestonesCompleted: t('partnerships.deliveryKpiMilestones'),
    phaseProgress: t('partnerships.deliveryPhaseProgress'),
    milestoneProgress: t('partnerships.deliveryMilestoneProgress'),
    taskProgress: t('partnerships.deliveryTaskProgress'),
    sessionProgress: t('partnerships.deliverySessionProgress'),
    deliverableProgress: t('partnerships.deliveryDeliverableProgress'),
    required: t('partnerships.deliveryRequired'),
    satisfied: t('partnerships.deliverySatisfied'),
    pending: t('partnerships.deliveryPending'),
    name: t('partnerships.deliveryFieldName'),
    owner: t('partnerships.sowOwner'),
    dueDate: t('partnerships.sowDueDate'),
    date: t('partnerships.deliveryFieldDate'),
    topic: t('partnerships.deliveryFieldTopic'),
    instructor: t('partnerships.deliveryFieldInstructor'),
    outcome: t('partnerships.deliveryFieldOutcome'),
    acceptanceCriteria: t('partnerships.sowAcceptanceCriteria'),
    severity: t('partnerships.deliveryFieldSeverity'),
    type: t('partnerships.deliveryFieldType'),
    impact: t('partnerships.deliveryFieldImpact'),
    mitigation: t('partnerships.deliveryFieldMitigation'),
    participants: t('partnerships.deliveryFieldParticipants'),
    subject: t('partnerships.deliveryFieldSubject'),
    summary: t('partnerships.deliveryFieldSummary'),
    actionItems: t('partnerships.deliveryFieldActionItems'),
    decisions: t('partnerships.deliveryFieldDecisions'),
    author: t('partnerships.deliveryFieldAuthor'),
    period: t('partnerships.deliveryFieldPeriod'),
  };
}
