import { DirectionService } from '../../../core/direction.service';
import type { ProposalPdfLabels } from './proposal-pdf';

/** Shared i18n labels for the school-facing Proposal PDF document. */
export function buildProposalPdfLabels(i18n: DirectionService): ProposalPdfLabels {
  const t = (key: string) => i18n.t(key);
  return {
    brand: t('brand.name'),
    documentTitle: t('partnerships.schoolPartnershipProposal'),
    initiative: t('partnerships.pdfTagline'),
    preparedFor: t('partnerships.pdfPreparedForSchool'),
    preparedBy: t('partnerships.pdfPreparedBy'),
    confidential: t('partnerships.pdfConfidential'),
    pageOf: t('partnerships.pdfPageOf'),
    proposalNo: t('partnerships.pdfProposalNo'),
    date: t('partnerships.pdfDate'),
    validUntil: t('partnerships.pdfValidUntil'),
    version: t('partnerships.version'),
    executiveSummary: t('partnerships.executiveSummary'),
    schoolGoals: t('partnerships.pdfSchoolGoals'),
    partnership: t('partnerships.pdfPartnership'),
    selectedOfferings: t('partnerships.pdfSelectedOfferings'),
    implementation: t('partnerships.pdfImplementation'),
    assessment: t('partnerships.pdfAssessment'),
    requirements: t('partnerships.pdfRequirements'),
    timeline: t('partnerships.pdfTimeline'),
    commercial: t('partnerships.pdfCommercial'),
    paymentTerms: t('partnerships.pdfPaymentTerms'),
    nextSteps: t('partnerships.pdfNextSteps'),
    terms: t('partnerships.pdfTerms'),
    learningExperience: t('partnerships.pdfLearningExperience'),
    outcomes: t('partnerships.proposalSectionOutcomes'),
    offering: t('partnerships.offering'),
    pricingBasis: t('partnerships.pdfPricingBasis'),
    qty: t('partnerships.pdfQty'),
    unitPrice: t('partnerships.pdfUnitPrice'),
    discount: t('partnerships.discount'),
    subtotal: t('partnerships.subtotal'),
    tax: t('partnerships.tax'),
    grandTotal: t('partnerships.grandTotal'),
    school: t('partnerships.school'),
    schoolChallenge: t('partnerships.schoolChallenge'),
    schoolObjective: t('partnerships.schoolObjective'),
    targetStudentGroup: t('partnerships.targetStudentGroup'),
    successCriteria: t('partnerships.successCriteria'),
    partnershipObjective: t('partnerships.partnershipObjective'),
    deliveryFormat: t('partnerships.deliveryFormat'),
    deliveryMode: t('partnerships.deliveryMode'),
    targetGrades: t('partnerships.targetGrades'),
    duration: t('partnerships.duration'),
    sessions: t('partnerships.numberOfSessions'),
    sessionLength: t('partnerships.sessionDurationMinutes'),
    level: t('partnerships.programLevel'),
    groupSize: t('partnerships.groupSizeMin'),
    groups: t('partnerships.numberOfGroups'),
    programName: t('partnerships.selectProgram'),
    schoolValue: t('partnerships.schoolValue'),
    studentValue: t('partnerships.studentValue'),
    required: t('partnerships.requirementRequired'),
    recommended: t('partnerships.requirementRecommended'),
    ctaTitle: t('partnerships.pdfCtaTitle'),
    ctaExplore: t('partnerships.pdfCtaExplore'),
    organization: t('partnerships.pdfOrganization'),
    continued: t('partnerships.pdfContinued'),
    minutes: t('partnerships.minutesShort'),
    customizedObjectives: t('partnerships.customizedObjectives'),
    customizedCurriculumNotes: t('partnerships.customizedCurriculumNotes'),
    specialRequirements: t('partnerships.specialRequirements'),
    implementationNotes: t('partnerships.implementationNotes'),
    deliveryNotes: t('partnerships.deliveryNotes'),
    curriculum: t('partnerships.offeringSectionCurriculum'),
    projects: t('partnerships.offeringSectionProjects'),
  };
}
